version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "06:00"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7
    groups:
      github:
        patterns:
          - "*"
