name: Dependabot auto-merge
on:
  workflow_call:
    inputs:
      minimum-age-of-pr:
        description: 'Minimum age of PR in days before automerging'
        required: false
        type: string
        default: '2'
      ignored-dependencies:
        description: 'Comma-separated list of dependencies to ignore'
        required: false
        type: string
        default: ''
      semver-filter:
        description: 'Semver filter for automerge (e.g., patch, minor, major)'
        required: false
        type: string
        default: 'patch,minor'
      always-allow:
        description: 'Comma-separated list of dependencies to always allow'
        required: false
        type: string
        default: ''
      auto-approve:
        description: 'Whether to automatically approve PRs before merging them'
        required: false
        type: boolean
        default: true
      merge-method:
        description: 'The merge method to use when merging pull requests (merge, squash, rebase)'
        required: false
        type: string
        default: 'merge'
  workflow_dispatch:

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: read
    outputs:
      merged-pr-count: ${{ steps.automerge.outputs.merged-pr-count }}
    steps:
      - name: Automerge Dependabot PRs
        id: automerge
        uses: navikt/automerge-dependabot@main
        with:
          token: ${{ github.token }}
          minimum-age-of-pr: ${{ inputs.minimum-age-of-pr }}
          blackout-periods: 'Sat,Sun,May 1,May 17,Dec 24-Jan 3'
          ignored-dependencies: ${{ inputs.ignored-dependencies }}
          semver-filter: ${{ inputs.semver-filter }}
          always-allow: ${{ inputs.always-allow }}
          auto-approve: ${{ inputs.auto-approve }}
          merge-method: ${{ inputs.merge-method }}

      - name: Automerge results
        run: |
          echo "Automerge Results:"
          echo "Number of merged PRs: ${{ steps.automerge.outputs.merged-pr-count }}"
          echo "Will trigger deploy: ${{ steps.automerge.outputs.merged-pr-count != '0' }}"

      - name: Run deploy workflow
        if: steps.automerge.outputs.merged-pr-count != '0'
        run: |
          gh api repos/${{ github.repository }}/dispatches \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -F "event_type=dependabot-deploy"
        env:
          GITHUB_TOKEN: ${{ github.token }}
