name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      team:
        required: false
        type: string
        description: Which Nais team's access token to use
        default: 'okonomi'
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '21'
      gradle-task:
        required: false
        type: string
        description: Gradle task to run
        default: './gradlew --configuration-cache build shadowJar'
      image-tag:
        required: false
        type: string
        description: Docker image tag
        default: 'latest'
    outputs:
      image:
        description: Google Artifact Registery image
        value: ${{ jobs.build-push-image.outputs.image }}

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # ratchet:actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # ratchet:actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - name: Build and test application
        uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # ratchet:gradle/actions/setup-gradle@v4
        env: # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        with:
          dependency-graph: generate-and-submit
      - run: ${{ inputs.gradle-task }}

      - name: Push Docker Image to GAR
        uses: nais/docker-build-push@078e460885ed0424b60d45ce9220b4be1748be9d # ratchet:nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: ${{ inputs.team }}
          tag: ${{ inputs.image-tag }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
