name: Build & test PR

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '21'
      gradle-task:
        required: false
        type: string
        description: Gradle task to run
        default: './gradlew --configuration-cache build shadowJar'

jobs:
  build-pr:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # ratchet:actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # ratchet:gradle/actions/setup-gradle@v6.3.0
      - run: ${INPUTS_GRADLE_TASK}
        env:
          INPUTS_GRADLE_TASK: ${{ inputs.gradle-task }}
