name: Build & test PR

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '21'
      gradle-task:
        required: false
        type: string
        description: Gradle task to run
        default: './gradlew --configuration-cache build shadowJar'

jobs:
  build-pr:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - uses: gradle/actions/setup-gradle@v4
      - run: ${{ inputs.gradle-task }}
