name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      team:
        required: false
        type: string
        description: Which Nais team's access token to use
        default: 'okonomi'
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '21'
      gradle-task:
        required: false
        type: string
        description: Gradle task to run
        default: './gradlew --configuration-cache build shadowJar'
      image-tag:
        required: false
        type: string
        description: Docker image tag
        default: 'latest'
      dockerfile:
        required: false
        type: string
        description: Path to the Dockerfile.
        default: 'Dockerfile'
    outputs:
      image:
        description: Google Artifact Registery image
        value: ${{ jobs.build-push-image.outputs.image }}

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.READER_TOKEN }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # ratchet:actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - name: Build and test application
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # ratchet:gradle/actions/setup-gradle@v6.3.0
        env: # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        with:
          dependency-graph: generate-and-submit
      - name: Run Gradle task
        env:
          GRADLE_TASK: ${{ inputs.gradle-task }}
        run: |
          bash -lc "$GRADLE_TASK"

      - name: Push Docker Image to GAR
        uses: nais/docker-build-push@2d2b0a7193e65422b7f0355d4afb445e0a8b2cc3 # ratchet:nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: ${{ inputs.team }}
          tag: ${{ inputs.image-tag }}
          dockerfile: ${{ inputs.dockerfile }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
