name: NAIS App Deploy

on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
        description: NAIS cluster to deploy to
      resource:
        required: true
        type: string
        description: NAIS resource to use for deployment
      image:
        required: true
        type: string
        description: Docker image to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Deploy to Environment
        uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: ${{ inputs.resource }}
          IMAGE: ${{ inputs.image }}
          TIMEOUT: 10m
          PRINT_PAYLOAD: true
