name: Security

on:
  workflow_call:
    inputs:
      team:
        required: false
        type: string
        description: Which Nais team's access token to use
        default: 'okonomi'
      language:
        required: true
        type: string
        description: 'Programming language to analyze (eg: java or javascript)'
      image-suffix:
        required: false
        type: string
        default: ''
        description: 'Optional suffix to append to the image name (no leading dash).'
      use-reader-token:
        required: false
        type: boolean
        default: false
        description: 'Tillater Gradle å hente private dependencies fra Github Packages'

env:
  LATEST_IMAGE: ${{ format('{0}{1}:latest', github.event.repository.name, inputs.image-suffix != '' && format('-{0}', inputs.image-suffix) || '') }}
  TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db:1"
  TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db"
  # Støtte for Gradle-prosjekter som har "val githubPassword: String by project" for å kunne hente private
  # dependencies fra GAR; fordrer at prosjekt-workflowen som kaller denne delte workflowen sender videre GITHUB_TOKEN
  # (f.eks. med "secrets: inherit")
  ORG_GRADLE_PROJECT_githubPassword: ${{ inputs.use-reader-token && secrets.READER_TOKEN || secrets.GITHUB_TOKEN }}

jobs:
  security-analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: ${{ inputs.language }}

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - uses: github/codeql-action/init@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@5595ccaf912efad79be6eef63a5619ff05969be3 # v4.37.6

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1
        with:
          category: "/language:${{ matrix.language }}"

      - name: Login to Google Artifact Registry
        uses: nais/login@40b72a35a18ddf2ad74b632461139ab838cc2a2f # v0
        id: login
        with:
          team: ${{ inputs.team }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: Run Trivy vulnerability scanner on docker image
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          image-ref: ${{ steps.login.outputs.registry }}/${{ env.LATEST_IMAGE }}
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@5595ccaf912efad79be6eef63a5619ff05969be3 # v4.37.6
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
